export const PRODUCTS = [
  {
    id: 1,
    name: "Наушники HyperX Cloud II",
    price: 49.99,
    image: "/products/headphones.jpg",
    desc: "Чистый звук и бас, удобная посадка.",
  },
  {
    id: 2,
    name: "Клавиатура SteelSeries Apex pro",
    price: 79.0,
    image: "/products/keybord.jpg",
    desc: "Механика, подсветка, быстрый отклик.",
  },
  {
    id: 3,
    name: "Мышь Logitech G Pro wireless",
    price: 25.5,
    image: "/products/mouse.jpg",
    desc: "Точный сенсор и удобная форма.",
  },
  {
    id: 4,
    name: "Монитор SunWind 27 SUN-M27BA108",
    price: 199.0,
    image: "/products/monitor.webp",
    desc: "IPS, 144Hz, сочные цвета.",
  },
    {
    id: 5,
    name: "Игровые наушники Logitech G435 Blue",
    price: 49.99,
    image: "/products/headphones2.webp",
    desc: "Чистый звук и бас, удобная посадка.",
  },
  {
    id: 6,
    name: "Клавиатура Varmilo Sea Melody V2 87",
    price: 79.0,
    image: "/products/keybord2.webp",
    desc: "Механика, подсветка, быстрый отклик.",
  },
  {
    id: 7,
    name: "Игровая мышь Logitech G402 Hyperion Fury USB Black",
    price: 25.5,
    image: "/products/mouse2.png",
    desc: "Точный сенсор и удобная форма.",
  },
  {
    id: 8,
    name: "Игровой монитор AOC G2 Series",
    price: 149.0,
    image: "/products/monitor2.jpg",
    desc: "Плоский игровой монитор, разрешение 3840 x 2160.",
  },
    {
    id: 9,
    name: "ASUS Наушники",
    price: 49.99,
    image: "/products/headphones6.jpg",
    desc: "Чистый звук и бас, удобная посадка.",
  },
  {
    id: 10,
    name: "Клавиатура Varmilo VA87M Panda Cherry MX Black",
    price: 79.0,
    image: "/products/keybord3.jpg",
    desc: "Механика, подсветка, быстрый отклик.",
  },
  {
    id: 11,
    name: "Игровая ышь Logitech G 102",
    price: 25.5,
    image: "/products/mouse3.webp",
    desc: "Точный сенсор и удобная форма.",
  },
  {
    id: 12,
    name: "Монитор Legendary Digital 27",
    price: 259.0,
    image: "/products/monitor3.jpg",
    desc: "Монитор для ПК IPS с дисплеем 144 Гц 2K",
  },
    {
    id: 13,
    name: "Logitech G435 LightSpeed White",
    price: 49.99,
    image: "/products/headphones3.webp",
    desc: "Чистый звук и бас, удобная посадка.",
  },
  {
    id: 14,
    name: "Клавиатура Anne pro 2",
    price: 79.0,
    image: "/products/keybord4.jpg",
    desc: "Механика, подсветка, быстрый отклик.",
  },
  {
    id: 15,
    name: "Игровая мышь Logitech G703 Lightspeed Wireless",
    price: 25.5,
    image: "/products/mouse4.jpg",
    desc: "Точный сенсор и удобная форма.",
  },
  {
    id: 16,
    name: "Игровой монитор ASUS VY249HGE Eye Care",
    price: 299.0,
    image: "/products/monitor4.jpg",
    desc: "24-дюймовый дисплей FHD IPS, 144 Гц, 1 мс, FreeSync Premium.",
  },
    {
    id: 17,
    name: "Игровые наушники Logitech G733 Lightspeed Wireless (",
    price: 49.99,
    image: "/products/headphones4.jpg",
    desc: "Чистый звук и бас, удобная посадка.",
  },
  {
    id: 18,
    name: "Клавиатура Redragon Ryze",
    price: 79.0,
    image: "/products/keybord5.webp",
    desc: "Механика, подсветка, быстрый отклик.",
  },
  {
    id: 19,
    name: "Игровая мышь Logitech G402 Hyperion Fury Black",
    price: 25.5,
    image: "/products/mouse5.webp",
    desc: "Точный сенсор и удобная форма.",
  },
  {
    id: 20,
    name: "AK 32 Монитор",
    price: 399.0,
    image: "/products/monitor5.jpg",
    desc: "4K 144Гц Fast IPS 3840x2160 UHD",
  },
    {
    id: 21,
    name: "Игровые наушники с микрофоном Audeze LCD-GX",
    price: 49.99,
    image: "/products/headphones5.jpg",
    desc: "Чистый звук и бас, удобная посадка.",
  },
  {
    id: 22,
    name: "Клавиатура MOTOSPEED K87S",
    price: 79.0,
    image: "/products/keybord6.jpeg",
    desc: "MOTOSPEED K87S Механическая клавиатура Игровая клавиатура Проводная игровая USB.",
  },
  {
    id: 23,
    name: "Razer DeathAdder Essential",
    price: 25.5,
    image: "/products/mouse6.jpg",
    desc: "Точный сенсор и удобная форма.",
  },
  {
    id: 24,
    name: "Китайский игровой монитор",
    price: 99.0,
    image: "/products/monitor6.jpg",
    desc: "38″ 2300R IPS 4K, монитор E-ports, монитор 4K, изогнутый",
  },
];